# Generated by Django 4.2.3 on 2023-07-10 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=43)),
                ('last_name', models.CharField(max_length=42)),
                ('title', models.CharField(choices=[('TM', 'Team Lead'), ('MD', 'Mid Lead'), ('JN', 'Junior')], max_length=100)),
                ('gender', models.CharField(choices=[('E', 'ERKEK'), ('K', 'KADIN')], max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('departman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personelApp.departman')),
            ],
        ),
    ]
