# Generated by Django 4.2.3 on 2023-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='salary',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
