# Generated by Django 4.2.3 on 2023-07-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personelApp', '0002_personel_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='departman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personel', to='personelApp.departman'),
        ),
    ]
