# Generated by Django 4.2.3 on 2023-07-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personelApp', '0003_alter_personel_departman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='title',
            field=models.CharField(choices=[('TM', 'Team Lead'), ('MD', 'Mid Lead'), ('JN', 'Junior')], default=3, max_length=100),
        ),
    ]
